name: CI

on:
  push:
    branches:
      - main
      - release/**

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - release/**
env:
  STEP_TIMEOUT_MINUTES: 60

jobs:
  smoke_test:
    name: Smoke Test (Debug Build of maERP)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        timeout-minutes: ${{ fromJSON(env.STEP_TIMEOUT_MINUTES) }}
        uses: "./.github/steps/install_dependencies"

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore Solution
        run: dotnet restore maERP.sln

      - name: Build maERP Solution (Debug)
        run: dotnet build maERP.sln --configuration Debug --no-restore

  unit_test:
    name: Unit Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        timeout-minutes: ${{ fromJSON(env.STEP_TIMEOUT_MINUTES) }}
        uses: "./.github/steps/install_dependencies"

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore Server Tests
        run: dotnet restore tests/maERP.Server.Tests/maERP.Server.Tests.csproj

      - name: Build Server Tests (Release)
        run: dotnet build tests/maERP.Server.Tests/maERP.Server.Tests.csproj --configuration Release --no-restore

      - name: Run Server Unit Tests
        run: dotnet test tests/maERP.Server.Tests/maERP.Server.Tests.csproj --no-build -c Release --logger GitHubActions --blame-crash --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: Restore Client Tests
        run: dotnet restore tests/maERP.Client.Tests/maERP.Client.Tests.csproj

      - name: Build Client Tests (Release)
        run: dotnet build tests/maERP.Client.Tests/maERP.Client.Tests.csproj --configuration Release --no-restore

      - name: Run Client Unit Tests
        run: dotnet test tests/maERP.Client.Tests/maERP.Client.Tests.csproj --no-build -c Release --logger GitHubActions --blame-crash --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
